# Generated by Django 4.0a1 on 2021-10-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_profile_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='checked',
            field=models.CharField(default='None', max_length=1),
        ),
    ]
