# Generated by Django 4.0a1 on 2021-10-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='checked',
            field=models.CharField(default=None, max_length=7),
        ),
    ]
